### ISSUE TITLE
Didnt work

### ISSUE THREAD

**Issue by gr0vx** [hishd/FacebookVideoExtractorAPI#1]
bro, i think this didnt work right now

**Comment by gr0vx** [comment]
> bro, i think this didnt work right now

sorry maybe i was wrong, This works, but sometimes shows a private video error message, after I tried again and finally it worked, what caused it to happen? Is it because of the limit or something? thanks bro this tool really helped me

**Comment by AbreuY** [comment]
@rizkyfarhanrr For private videos you need to find the logic to use cookies.

**Comment by hishd** [comment]
@AbreuY you are correct..!

**Comment by hishd** [comment]
@rizkyfarhanrr what is the error that you are getting...?

**Comment by gr0vx** [comment]
> @rizkyfarhanrr For private videos you need to find the logic to use cookies.

@hishd , like this guy said bro
